CREATE TABLE `signature-verification`.`event_source` (
  `business_key` VARCHAR(45) NOT NULL,
  `application` VARCHAR(45) NULL,
  `comments` VARCHAR(45) NULL,
  `transaction_currency` VARCHAR(45) NULL,
  `transaction_amount` INT NULL,
  `amount_in_mur` INT NULL,
  `debit_account_number` VARCHAR(45) NULL,
  `account_short_name` VARCHAR(45) NULL,
  `debit_account_ccy` VARCHAR(45) NULL,
  `payment_details_1` VARCHAR(45) NULL,
  `payment_details_2` VARCHAR(45) NULL,
  `payment_details_3` VARCHAR(45) NULL,
  `payment_details_4` VARCHAR(45) NULL,
  `source_bu` VARCHAR(45) NULL,
  `verfied` VARCHAR(45) NULL,
  `discrepancy_reason` VARCHAR(45) NULL,
  `created_by` VARCHAR(45) NULL,
  `created_on` DATETIME(6) NOT NULL,
  `updated_by` VARCHAR(45) NULL,
  `updated_on` VARCHAR(6) NOT NULL,
  `priority` VARCHAR(45) NULL,
  `document_capture_reference` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`business_key`));
